spring:
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:sample;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;TRACE_LEVEL_SYSTEM_OUT=1;INIT=RUNSCRIPT from 'classpath:sql/db_init.h2.sql'
        username: dbuser
        password: dbuser
        max-wait: 1000
        max-active: 50
        test-on-borrow: false
        validation-query: SELECT 1
        validation-interval: 500
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        database: H2

broker:
    zookeeper: ec2-52-91-88-55.compute-1.amazonaws.com:2181
    producer:
        bootstrapServer: ec2-52-91-88-55.compute-1.amazonaws.com:9092
        linger-time-ms: 0
    consumer:
        bootstrapServer: ec2-52-91-88-55.compute-1.amazonaws.com:9092
